/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CourierRouteImport } from './routes/courier'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ApiPublicMenuImageRouteImport } from './routes/api/public/menu-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierRoute = CourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMenuImageRoute = ApiPublicMenuImageRouteImport.update({
  id: '/api/public/menu-image',
  path: '/api/public/menu-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/api/public/menu-image': typeof ApiPublicMenuImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/api/public/menu-image': typeof ApiPublicMenuImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courier': typeof CourierRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/api/public/menu-image': typeof ApiPublicMenuImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courier'
    | '/dashboard'
    | '/menu'
    | '/order'
    | '/api/public/menu-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courier'
    | '/dashboard'
    | '/menu'
    | '/order'
    | '/api/public/menu-image'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/courier'
    | '/dashboard'
    | '/menu'
    | '/order'
    | '/api/public/menu-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CourierRoute: typeof CourierRoute
  DashboardRoute: typeof DashboardRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  ApiPublicMenuImageRoute: typeof ApiPublicMenuImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier': {
      id: '/courier'
      path: '/courier'
      fullPath: '/courier'
      preLoaderRoute: typeof CourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/menu-image': {
      id: '/api/public/menu-image'
      path: '/api/public/menu-image'
      fullPath: '/api/public/menu-image'
      preLoaderRoute: typeof ApiPublicMenuImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CourierRoute: CourierRoute,
  DashboardRoute: DashboardRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  ApiPublicMenuImageRoute: ApiPublicMenuImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
